<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEaGCrdm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEaGCrdm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEaGCrdm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEaGCrdm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEaGCrdm\App_KernelDevDebugContainer([
    'container.build_hash' => 'EaGCrdm',
    'container.build_id' => '1548f574',
    'container.build_time' => 1674570812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEaGCrdm');
